/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const HttpError = t.iface([], {
    "title": "string",
    "status": "number",
    "details": "string",
    "developerMessage": "string",
    "timestamp": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
    HttpError,
};
export default exportedTypeSuite;
