/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const Token = t.iface([], {
    token: 'string',
    expirationDate: t.union('string', 'number'),
});

const exportedTypeSuite: t.ITypeSuite = {
    Token,
};
export default exportedTypeSuite;
